//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isima.InstantMessaging.WcfClient.SessionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Isima.InstantMessaging.WcfService")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InstantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Instant {
            get {
                return this.InstantField;
            }
            set {
                if ((this.InstantField.Equals(value) != true)) {
                    this.InstantField = value;
                    this.RaisePropertyChanged("Instant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverAddress {
            get {
                return this.ReceiverAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverAddressField, value) != true)) {
                    this.ReceiverAddressField = value;
                    this.RaisePropertyChanged("ReceiverAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderAddress {
            get {
                return this.SenderAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderAddressField, value) != true)) {
                    this.SenderAddressField = value;
                    this.RaisePropertyChanged("SenderAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://schemas.datacontract.org/2004/07/Isima.InstantMessaging.WcfService")]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdentifiantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WindowsIdentityNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Expiration {
            get {
                return this.ExpirationField;
            }
            set {
                if ((this.ExpirationField.Equals(value) != true)) {
                    this.ExpirationField = value;
                    this.RaisePropertyChanged("Expiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Identifiant {
            get {
                return this.IdentifiantField;
            }
            set {
                if ((this.IdentifiantField.Equals(value) != true)) {
                    this.IdentifiantField = value;
                    this.RaisePropertyChanged("Identifiant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WindowsIdentityName {
            get {
                return this.WindowsIdentityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WindowsIdentityNameField, value) != true)) {
                    this.WindowsIdentityNameField = value;
                    this.RaisePropertyChanged("WindowsIdentityName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SessionServiceReference.ISessionService")]
    public interface ISessionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/SendMessage", ReplyAction="http://tempuri.org/ISessionService/SendMessageResponse")]
        bool SendMessage(Isima.InstantMessaging.WcfClient.SessionServiceReference.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/GetMessage", ReplyAction="http://tempuri.org/ISessionService/GetMessageResponse")]
        Isima.InstantMessaging.WcfClient.SessionServiceReference.Message[] GetMessage(string adresse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Register", ReplyAction="http://tempuri.org/ISessionService/RegisterResponse")]
        Isima.InstantMessaging.WcfClient.SessionServiceReference.Session Register(System.DateTime current);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/GetPresence", ReplyAction="http://tempuri.org/ISessionService/GetPresenceResponse")]
        bool GetPresence(string windowsIdentityName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISessionServiceChannel : Isima.InstantMessaging.WcfClient.SessionServiceReference.ISessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionServiceClient : System.ServiceModel.ClientBase<Isima.InstantMessaging.WcfClient.SessionServiceReference.ISessionService>, Isima.InstantMessaging.WcfClient.SessionServiceReference.ISessionService {
        
        public SessionServiceClient() {
        }
        
        public SessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendMessage(Isima.InstantMessaging.WcfClient.SessionServiceReference.Message message) {
            return base.Channel.SendMessage(message);
        }
        
        public Isima.InstantMessaging.WcfClient.SessionServiceReference.Message[] GetMessage(string adresse) {
            return base.Channel.GetMessage(adresse);
        }
        
        public Isima.InstantMessaging.WcfClient.SessionServiceReference.Session Register(System.DateTime current) {
            return base.Channel.Register(current);
        }
        
        public bool GetPresence(string windowsIdentityName) {
            return base.Channel.GetPresence(windowsIdentityName);
        }
    }
}
